"""created stuff and link

Revision ID: 5679a33d16dc
Revises: 7191be88bd7c
Create Date: 2025-06-07 18:00:29.556693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5679a33d16dc'
down_revision: Union[str, None] = '7191be88bd7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stuff',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stuff_id'), 'stuff', ['id'], unique=False)
    op.create_table('invoicestufflink',
    sa.Column('stuff_id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.ForeignKeyConstraint(['stuff_id'], ['stuff.id'], ),
    sa.PrimaryKeyConstraint('stuff_id', 'invoice_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoicestufflink')
    op.drop_index(op.f('ix_stuff_id'), table_name='stuff')
    op.drop_table('stuff')
    # ### end Alembic commands ###
